# SITE CONFIGURATION
#baseurl: "/"
url: "https://blog.codingblocks.xyz/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Coding Blocks Blog
  avatar: logo.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
    <blockquote>
     <p> “Any fool can write code that a computer can understand. Good programmers write code that humans can understand.”</p>

     <footer>- Martin Fowler</footer>
     </blockquote>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: admissions@codingblocks.com
  behance:
  bitbucket:
  dribbble:
  facebook: "codingblocksindia"
  flickr:
  github: "coding-blocks"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "codingblocksIN"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-83327907-2"
  disqus_shortname: championswimmer
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

#Pages
include: ['pages']

# BUILD SETTINGS
#markdown: kramdown
#highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
